### ISSUE TITLE
Error during test Undefined array key "collation"

### ISSUE THREAD

**Issue by newbelaravel** [codezero-be/laravel-unique-translation#23]
Hi! 
Fantastic package. Works great during browser usage, but I get a really weird error when testing the form I want to validate. 
Basics:
I am using Laravel-translatable from Spatie and want to check that the title is unique in a JSON column for a specific locale. My form is really simple:
```
<label>TítuloES</label><br>
<input class="border" type="text" name="title[es]"><br>
<label>TítuloEN</label><br>
<input class="border" type="text" name="title[en]"><br>
```
My validation looks like this:
```
 $attributes = request()->validate([
            'title.*' => 'required|max:255|unique_translation:posts,title',
            'summary.*' => 'required',
            'content.*' => 'required',
            'imagetitle' => [
                'sometimes', 
                'mimes:jpeg,jpg,png'
                ]
        ]);
```

When I use the web, it works, but when I test it, I get a super long error, but the most important part seems this one:
```
The following exception occurred during the last request:

ErrorException: Undefined array key "collation" in E:\Programas\laragon\www\webtronica\vendor\codezero\laravel-unique-translation\src\UniqueTranslationValidator.php:238
Stack trace:
#0 E:\Programas\laragon\www\myapp\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(259): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Undefined array...', 'E:\\Programas\\la...', 238)
#1 E:\Programas\laragon\www\myapp\vendor\codezero\laravel-unique-translation\src\UniqueTranslationValidator.php(238): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'Undefined array...', 'E:\\Programas\\la...', 238)
#2 E:\Programas\laragon\www\myapp\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1551): CodeZero\UniqueTranslation\UniqueTranslationValidator->CodeZero\UniqueTranslation\{closure}(Object(Illuminate\Database\Query\Builder))
```

I guess the package is trying to get some info from the DB, but it is not getting it. Then, everything breaks. So, I have 2 questions:
Should I somehow modify configuration of PHP unit? Now it looks like this:
```
  <php>
    <server name="APP_ENV" value="testing"/>
    <server name="BCRYPT_ROUNDS" value="4"/>
    <server name="CACHE_DRIVER" value="array"/>
    <server name="DB_CONNECTION" value="sqlite"/>
    <server name="DB_DATABASE" value=":memory:"/>
    <server name="MAIL_DRIVER" value="array"/>
    <server name="QUEUE_CONNECTION" value="sync"/>
    <server name="SESSION_DRIVER" value="array"/>
    <env name="DB_CONNECTION" value="sqlite"/>
    <env name="RECAPTCHA_KEY" value="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"/>
    <env name="RECAPTCHA_SECRET" value="6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"/>
  </php>
</phpunit>
```
Question number 2: when using browser and submitting the form, no error is seen and the post is created with success. 
The collation fields of my database are empty, so I don't understand how its working:
![imagen](https://user-images.githubusercontent.com/7984653/209703887-0a003250-c3fe-43b9-b1da-f5a2f6756af7.png)

Many thanks!!!

**Comment by ivanvermeyen** [comment]
Hi,

Thanks for reporting!

This is probably introduced by this commit:
[Enable case-insensitive search in MySQL 8.7+ JSON fields](https://github.com/codezero-be/laravel-unique-translation/commit/07fd050e3b83d65a2e8c937701df123eeb360eb3)

It grabs the collation from the database config.
So far, I don't have this issue when testing locally, but it might depend on the testing framework.

I'll look into it.

**Comment by newbelaravel** [comment]
Thank you very much @ivanvermeyen. I'll add more details to help you:

- I just tested with the previous version of the method and it worked. This one:
```
    protected function findTranslation($connection, $table, $column, $locale, $value)
    {
        // Properly escape backslashes to work with LIKE queries...
        // See: https://stackoverflow.com/questions/14926386/how-to-search-for-slash-in-mysql-and-why-escaping-not-required-for-wher
        $value = str_replace('\\', '\\\\\\\\', $value);

        return DB::connection($connection)->table($table)
            ->where(function ($query) use ($column, $locale, $value) {
                $query->where($column, 'LIKE', "%\"{$locale}\": \"{$value}\"%")
                    ->orWhere($column, 'LIKE', "%\"{$locale}\":\"{$value}\"%");
            });
    }
```

- When browsing manually in the dev server (laragon with MySQL 5.7.24) it works absolutely great.
- Only when testing with phpunit with the default laravel config (or at least it was default when I started the project) it fails. The DB config is in PHP unit
```
    <server name="DB_CONNECTION" value="sqlite"/>
    <server name="DB_DATABASE" value=":memory:"/>
```
And the config in laravel config/database.php for this database is
```
        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DATABASE_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],
```
I think the problem is the definition of "collation", that is non existant. The issue is that I am not able to think a way to ¿fake? the value during tests and also don't understand why it works when manually browsing because my dev database doesn't have a collation value either (maybe it returns a default one in this case?)

Thanks for your support

**Comment by newbelaravel** [comment]
Also, I tried modfiying the DB configuration at laravel config/database.php adding two lines with charset and collation. Resulting this:
```
        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DATABASE_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],
```

It does not work still, but the error message is different:
```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 near &quot;&gt;&quot;: syntax error (SQL: select count(*) as aggregate from &quot;posts&quot; where (title-&gt;&quot;$.en&quot; COLLATE utf8mb4_unicode_ci = &quot;ENEt aut.&quot;)) in file E:\Programas\laragon\www\webtronica\vendor\laravel\framework\src\Illuminate\Database\Connection.php on line 760\n
\n
#0 E:\Programas\laragon\www\webtronica\vendor\laravel\framework\src\Illuminate\Database\Connection.php(720): Illuminate\Database\Connection-&gt;runQueryCallback('select count(*)...', Array, Object(Closure))\n  
#1 E:\Programas\laragon\www\webtronica\vendor\laravel\framework\src\Illuminate\Database\Connection.php(422): Illuminate\Database\Connection-&gt;run('select count(*)...', Array, Object(Closure))\n
#2 E:\Programas\laragon\www\webtronica\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2650): Illuminate\Database\Connection-&gt;select('select count(*)...', Array, true)\n
#3 E:\Programas\laragon\www\webtronica\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2638): Illuminate\Database\Query\Builder-&gt;runSelect()\n
#4 E:\Programas\laragon\www\webtronica\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(3174): Illuminate\Database\Query\Builder-&gt;Illuminate\Database\Query\{closure}()\n
#5 E:\Programas\laragon\www\webtronica\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2639): Illuminate\Database\Query\Builder-&gt;onceWithColumns(Array, Object(Closure))\n
#6 E:\Programas\laragon\www\webtronica\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(3101): Illuminate\Database\Query\Builder-&gt;get(Array)\n
#7 E:\Programas\laragon\www\webtronica\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(3029): Illuminate\Database\Query\Builder-&gt;aggregate('count', Array)\n
#8 E:\Programas\laragon\www\webtronica\vendor\codezero\laravel-unique-translation\src\UniqueTranslationValidator.php(214): Illuminate\Database\Query\Builder-&gt;count()\n
#9 E:\Programas\laragon\www\webtronica\vendor\codezero\laravel-unique-translation\src\UniqueTranslationValidator.php(28): CodeZero\UniqueTranslation\UniqueTranslationValidator-&gt;isUnique('ENEt aut.', 'title', 'en', Array)\n
#10 E:\Programas\laragon\www\webtronica\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1516): CodeZero\UniqueTranslation\UniqueTranslationValidator-&gt;validate('title.en', 'ENEt aut.', Array, Object(Illuminate\Validation\Validator))\n
```

It is a bit hard to see, but line 8 and 9 come from this package. I do not say this to blame in any way, just for info. 
Probably, the modification I made in DB config to add collation did not make sense in a SQLite DB.
Thanks

**Comment by ivanvermeyen** [comment]
Ah, I see.
The JSON query syntax (column->$locale) is not supported by SQLite as far as I know.
I always used MySQL for testing this package, so I didn't notice.
It's an unfortunate side effect though, but I don't know another way to achieve the [case-insensitive query](https://github.com/codezero-be/laravel-unique-translation/issues/8).

**Comment by newbelaravel** [comment]
Hi again,
Thanks for identifying the problem. As SQLite is not supported by the package, I guess no modification in source is expected. Just to provide some closure and for others that may face this issue, I just confirm that after changing the test database from SQLite to MySQL it worked (I created a new database for testing). I leave the PHP unit config here for the record:
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="false" backupStaticAttributes="false" bootstrap="vendor/autoload.php" colors="true" convertErrorsToExceptions="true" convertNoticesToExceptions="true" convertWarningsToExceptions="true" processIsolation="false" stopOnFailure="false">
  <coverage processUncoveredFiles="true">
    <include>
      <directory suffix=".php">./app</directory>
    </include>
  </coverage>
  <testsuites>
    <testsuite name="Unit">
      <directory suffix="Test.php">./tests/Unit</directory>
    </testsuite>
    <testsuite name="Feature">
      <directory suffix="Test.php">./tests/Feature</directory>
    </testsuite>
  </testsuites>
  <php>
    <server name="APP_ENV" value="testing"/>
    <env name="DB_CONNECTION" value="mysql"/>
    <env name="DB_HOST" value="127.0.0.1"/>
    <env name="DB_PORT" value="3306"/>
    <env name="DB_DATABASE" value="test_laravel"/>
    <env name="DB_USERNAME" value="root" />
    <env name="DB_PASSWORD" value="" />
  </php>
</phpunit>
```

Feel free to close the issue unless you want to support SQLite :-)
Thanks!

**Comment by ivanvermeyen** [comment]
Reverted back to using a `LIKE` query, as this is also case insensitive (which was the whole point).
All tests run fine now on MySQL and SQLite, except one for arabic language. 
So for testing purposes you should now be fine using SQLite "unofficially". 👍

https://github.com/codezero-be/laravel-unique-translation/releases/tag/4.1.1
